exclude: (?x)^src/(lua/.+|miniz/.+|spng/.+|stb/.+|wave/.+|woodyopl/.+|siphash/.+|physfs/.+)$
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file:.clang-format", "-i"]
      # not really working because DOS code
      #- id: clang-tidy
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua-github
        
      
